In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data = pd.read_csv("../data/Inpatient_Psychiatric_Facility_Quality_Measure_Data___by_Facility.csv")
print(raw_data.shape)
raw_data.head()

(1644, 85)

,Provider_Number,Hospital_Name,Address,City,State,ZIP_Code,County_Name,HBIPS-2_Measure_Description,HBIPS-2_Overall_Rate_Per_1000,HBIPS-2_Overall_Num,...,IMM-2_Numerator,IMM-2_Denominator,IMM-2_Footnote,HCP_Measure_Description,HCP_%,HCP_Numerator,HCP_Denominator,HCP_Footnote,Flu_Season_Start_Date,Flu_Season_End_Date
0,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN STREET PO BOX 1010,OPP,AL,36467,Covington,Hours of physical-restraint use,0.00,0.00,...,50,128,NaN,Healthcare Personnel Influenza Vaccination,54,15,28,NaN,10/01/2015,03/31/2016
1,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,Crenshaw,Hours of physical-restraint use,0.44,59.63,...,88,88,NaN,Healthcare Personnel Influenza Vaccination,34,15,44,NaN,10/01/2015,03/31/2016
2,10011,ST. VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,Jefferson,Hours of physical-restraint use,0.00,0.00,...,54,80,NaN,Healthcare Personnel Influenza Vaccination,42,14,33,NaN,10/01/2015,03/31/2016
3,10012,DEKALB REGIONAL MEDICAL CENTER,200 MED CENTER DRIVE,FORT PAYNE,AL,35968,DeKalb,Hours of physical-restraint use,0.00,0.00,...,105,106,NaN,Healthcare Personnel Influenza Vaccination,100,54,54,NaN,10/01/2015,03/31/2016
4,10016,SHELBY BAPTIST MEDICAL CENTER,1000 FIRST STREET NORTH,ALABASTER,AL,35007,Shelby,Hours of physical-restraint use,0.11,41.02,...,171,171,NaN,Healthcare Personnel Influenza Vaccination,71,65,92,NaN,10/01/2015,03/31/2016

In [3]:
raw_data.to_csv('../output/out.csv')

In [4]:
#checking for missing values

# from https://github.com/WillKoehrsen/machine-learning-project-walkthrough
# /blob/master/Machine%20Learning%20Project%20Part%201.ipynb# from  
# Function to calculate missing values by column# Funct 
def missing_values_table(df):
        # Total missing values
        mis_val = df.isnull().sum()
        
        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        
        # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        
        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        
        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        # Print some summary information
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        
        # Return the dataframe with missing information
        return mis_val_table_ren_columns

In [5]:
missing_values_table(raw_data)

Your selected dataframe has 85 columns.
There are 21 columns that have missing values.

                               Missing Values  % of Total Values
HIE_Footnote                             1626               98.9
EHR_Use_Footnote                         1626               98.9
PEoC_Assessed_Footnote                   1626               98.9
HBIPS-2_Overall_Footnote                 1613               98.1
HBIPS-6_Overall_Footnote                 1611               98.0
HBIPS-3_Overall_Footnote                 1609               97.9
HBIPS-7_Overall_Footnote                 1603               97.5
TOB-1_Footnote                           1586               96.5
SUB-1_Footnote                           1569               95.4
IMM-2_Footnote                           1548               94.2
HCP_Footnote                             1548               94.2
TOB-2_Footnote                           1390               84.5
FUH-30_Footnote                          1348               82.0
TOB-2a_Footnote                          1196               72.7
FUH-7_Footnote                           1144               69.6
HBIPS-5_Overall_%_of_Total                939               57.1
HBIPS-5_Overall_Footnote                  705               42.9
HBIPS-3_Overall_Rate_Per_1000              35                2.1
HBIPS-2_Overall_Rate_Per_1000              31                1.9
HBIPS-2_Overall_Num                        15                0.9
HBIPS-2_Overall_Den                        15                0.9

In [8]:
def drop_missing_values(df, percent_drop):
    """
    Drop columns with missing values.
    
    Args:
        df = dataframe
        percent_drop = percentage of null values above which the column will be dropped
            as decimal between 0 and 1
    Returns:
        df = df where columns above percent_drop are dropped.
    
    """
    to_drop = [column for column in df if (df[column].isnull().sum()/len(df) >= percent_drop)]

    print('Columns to drop: ' , (len(to_drop)))
    # Drop features 
    df = df.drop(columns=to_drop)
    print('Shape: ', df.shape)
    return df

In [10]:
# dropping missing values for percent over 60%
# first make a copy to avoid changing the original dataset
df = raw_data.copy()
df = drop_missing_values(df, .60)

Columns to drop:  15
Shape:  (1644, 70)

In [ ]:
df.head()

In [11]:
df.columns

Index(['Provider_Number', 'Hospital_Name', 'Address', 'City', 'State',
       'ZIP_Code', 'County_Name', 'HBIPS-2_Measure_Description',
       'HBIPS-2_Overall_Rate_Per_1000', 'HBIPS-2_Overall_Num',
       'HBIPS-2_Overall_Den', 'HBIPS-3_Measure_Description',
       'HBIPS-3_Overall_Rate_Per_1000', 'HBIPS-3_Overall_Num',
       'HBIPS-3_Overall_Den', 'HBIPS-5_Measure_Description',
       'HBIPS-5_Overall_%_of_Total', 'HBIPS-5_Overall_Num',
       'HBIPS-5_Overall_Den', 'HBIPS-5_Overall_Footnote',
       'HBIPS-6_Measure_Description', 'HBIPS-6_Overall_%_of_Total',
       'HBIPS-6_Overall_Num', 'HBIPS-6_Overall_Den',
       'HBIPS-7_Measure_Description', 'HBIPS-7_Overall_%_of_Total',
       'HBIPS-7_Overall_Num', 'HBIPS-7_Overall_Den',
       'SUB-1_Measure_Description', 'SUB-1_%', 'SUB-1_Numerator',
       'SUB-1_Denominator', 'TOB-1_Measure_Description', 'TOB-1_%',
       'TOB-1_Numerator', 'TOB-1_Denominator', 'TOB-2/-2a_Measure_Desc',
       'TOB-2_%', 'TOB-2_Numerator', 'TOB-2/-2a_Denominator', 'TOB-2a_%',
       'TOB-2a_Numerator', 'TOB-2/-2a__Denominator',
       'PEoC_Measure_Description', 'PEoC_Assessed_Response',
       'EHR_Use_Measure_Description', 'EHR_Use_Response',
       'HIE_Measure_Description', 'HIE_Response', 'Start_Date', 'End_Date',
       'FUH_Measure_Description', 'FUH-30_%', 'FUH-30_Numerator',
       'FUH-30_Denominator', 'FUH-7_%', 'FUH-7_Numerator', 'FUH-7_Denominator',
       'FUH_Measure_Start_Date', 'FUH_Measure_End_Date',
       'IMM-2_Measure_Description', 'IMM-2_%', 'IMM-2_Numerator',
       'IMM-2_Denominator', 'HCP_Measure_Description', 'HCP_%',
       'HCP_Numerator', 'HCP_Denominator', 'Flu_Season_Start_Date',
       'Flu_Season_End_Date'],
      dtype='object')

In [13]:
# dropping additional columns
df = df.drop(['HBIPS-2_Measure_Description',
              'HBIPS-3_Measure_Description',
              'HBIPS-5_Measure_Description',
              'HBIPS-6_Measure_Description',
              'HBIPS-5_Overall_Footnote',
              'HBIPS-7_Measure_Description',
              'SUB-1_Measure_Description',
              'TOB-1_Measure_Description',
              'TOB-2/-2a_Measure_Desc',
              'PEoC_Measure_Description',
              'EHR_Use_Measure_Description',
              'HIE_Measure_Description',
              'FUH_Measure_Description',
              'IMM-2_Measure_Description',
              'HCP_Measure_Description',
             ], axis=1)

In [14]:
df.head()

,Provider_Number,Hospital_Name,Address,City,State,ZIP_Code,County_Name,HBIPS-2_Overall_Rate_Per_1000,HBIPS-2_Overall_Num,HBIPS-2_Overall_Den,...,FUH_Measure_Start_Date,FUH_Measure_End_Date,IMM-2_%,IMM-2_Numerator,IMM-2_Denominator,HCP_%,HCP_Numerator,HCP_Denominator,Flu_Season_Start_Date,Flu_Season_End_Date
0,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN STREET PO BOX 1010,OPP,AL,36467,Covington,0.00,0.00,3513.0,...,07/01/2014,06/30/2015,39.06%,50,128,54,15,28,10/01/2015,03/31/2016
1,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,Crenshaw,0.44,59.63,5611.0,...,07/01/2014,06/30/2015,100.00%,88,88,34,15,44,10/01/2015,03/31/2016
2,10011,ST. VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,Jefferson,0.00,0.00,24771.0,...,07/01/2014,06/30/2015,67.50%,54,80,42,14,33,10/01/2015,03/31/2016
3,10012,DEKALB REGIONAL MEDICAL CENTER,200 MED CENTER DRIVE,FORT PAYNE,AL,35968,DeKalb,0.00,0.00,5832.0,...,07/01/2014,06/30/2015,99.06%,105,106,100,54,54,10/01/2015,03/31/2016
4,10016,SHELBY BAPTIST MEDICAL CENTER,1000 FIRST STREET NORTH,ALABASTER,AL,35007,Shelby,0.11,41.02,15507.0,...,07/01/2014,06/30/2015,100.00%,171,171,71,65,92,10/01/2015,03/31/2016

In [16]:
df.columns

Index(['Provider_Number', 'Hospital_Name', 'Address', 'City', 'State',
       'ZIP_Code', 'County_Name', 'HBIPS-2_Overall_Rate_Per_1000',
       'HBIPS-2_Overall_Num', 'HBIPS-2_Overall_Den',
       'HBIPS-3_Overall_Rate_Per_1000', 'HBIPS-3_Overall_Num',
       'HBIPS-3_Overall_Den', 'HBIPS-5_Overall_%_of_Total',
       'HBIPS-5_Overall_Num', 'HBIPS-5_Overall_Den',
       'HBIPS-6_Overall_%_of_Total', 'HBIPS-6_Overall_Num',
       'HBIPS-6_Overall_Den', 'HBIPS-7_Overall_%_of_Total',
       'HBIPS-7_Overall_Num', 'HBIPS-7_Overall_Den', 'SUB-1_%',
       'SUB-1_Numerator', 'SUB-1_Denominator', 'TOB-1_%', 'TOB-1_Numerator',
       'TOB-1_Denominator', 'TOB-2_%', 'TOB-2_Numerator',
       'TOB-2/-2a_Denominator', 'TOB-2a_%', 'TOB-2a_Numerator',
       'TOB-2/-2a__Denominator', 'PEoC_Assessed_Response', 'EHR_Use_Response',
       'HIE_Response', 'Start_Date', 'End_Date', 'FUH-30_%',
       'FUH-30_Numerator', 'FUH-30_Denominator', 'FUH-7_%', 'FUH-7_Numerator',
       'FUH-7_Denominator', 'FUH_Measure_Start_Date', 'FUH_Measure_End_Date',
       'IMM-2_%', 'IMM-2_Numerator', 'IMM-2_Denominator', 'HCP_%',
       'HCP_Numerator', 'HCP_Denominator', 'Flu_Season_Start_Date',
       'Flu_Season_End_Date'],
      dtype='object')

In [20]:
# renaming columns
df = df.rename({'SUB-1_%':'Alcohol Screen Complete %',
                'SUB-1_Numerator':'Alcohol Screen Numerator',
                'SUB-1_Denominator':'Alcohol Screen Denominator',
                'TOB-2_%':'Tobacco Use Screen %',
                'EHR_Use_Response':'EHR Use',
                'FUH-30_%':'% Patients Follow Up Care within 30 days',
                'FUH-7_%':'% Patients Follow Up Care within 7 days for mental illness',
                
                'HBIPS-2_Overall_Rate_Per_1000':'Hours physical restraint rate per 1000',
                'HBIPS-2_Overall_Num':'Hours physical restraint',
                'HBIPS-2_Overall_Den':'Total inpatient hours',
                
                'HBIPS-3_Overall_Rate_Per_1000':'Hours seclusion rate per 1000',
                'HBIPS-3_Overall_Num':'Hours seclusion',
                'HBIPS-3_Overall_Den':'Total inpatient hours',
                
                'HBIPS-5_Overall_%_of_Total':'Discharged 2+ meds %',
                'HBIPS-5_Overall_Num':'Discharged 2+ meds with justification',
                'HBIPS-5_Overall_Den':'Discharged 2+ meds total',
                
                'HBIPS-6_Overall_%_of_Total':'Post discharge continuing care plan %',
                'HBIPS-6_Overall_Num':'Post discharge continuing care plan created',
                'HBIPS-6_Overall_Den':'Total discharge patients',
                
                'HBIPS-7_Overall_%_of_Total':'Continuing care plan sent to next provider %',
                'HBIPS-7_Overall_Num':'Continuing care plan sent to next provider',
                'HBIPS-7_Overall_Den':'Total continuing care plans'
                
               }, axis=1)

In [21]:
df.head()

,Provider_Number,Hospital_Name,Address,City,State,ZIP_Code,County_Name,Hours physical restraint rate per 1000,Hours physical restraint,Total inpatient hours,...,FUH_Measure_Start_Date,FUH_Measure_End_Date,IMM-2_%,IMM-2_Numerator,IMM-2_Denominator,HCP_%,HCP_Numerator,HCP_Denominator,Flu_Season_Start_Date,Flu_Season_End_Date
0,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN STREET PO BOX 1010,OPP,AL,36467,Covington,0.00,0.00,3513.0,...,07/01/2014,06/30/2015,39.06%,50,128,54,15,28,10/01/2015,03/31/2016
1,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,Crenshaw,0.44,59.63,5611.0,...,07/01/2014,06/30/2015,100.00%,88,88,34,15,44,10/01/2015,03/31/2016
2,10011,ST. VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,Jefferson,0.00,0.00,24771.0,...,07/01/2014,06/30/2015,67.50%,54,80,42,14,33,10/01/2015,03/31/2016
3,10012,DEKALB REGIONAL MEDICAL CENTER,200 MED CENTER DRIVE,FORT PAYNE,AL,35968,DeKalb,0.00,0.00,5832.0,...,07/01/2014,06/30/2015,99.06%,105,106,100,54,54,10/01/2015,03/31/2016
4,10016,SHELBY BAPTIST MEDICAL CENTER,1000 FIRST STREET NORTH,ALABASTER,AL,35007,Shelby,0.11,41.02,15507.0,...,07/01/2014,06/30/2015,100.00%,171,171,71,65,92,10/01/2015,03/31/2016

In [23]:
df.to_csv('Inpatient_Psychiatric_Facility_Quality_Measure_Data_Cleaned.csv')